### ISSUE TITLE
Entities removed in TU worlds

### ISSUE THREAD

**Issue by Ineedmyentities** [ViolaFlower/Re-Console#100]
The best parts of the worlds are gone, all entities were wiped. When downloading the TU worlds off the internet the entities are present. Chests in TU1 are empty. Item frames in all worlds seem to be gone., along with the farm animals.

**Comment by omo50** [comment]
If you do not reply with any information in 3 days im just going to close this

**Comment by Ineedmyentities** [comment]
I noticed it specifically in 1.21On Jul 31, 2024, at 03:57, bowen ***@***.***> wrote:﻿
If you do not reply with any information in 3 days im just going to close this

**Comment by omo50** [comment]
fixed in 0.7.3
