### ISSUE TITLE
in need of a 1.21 panorama

### ISSUE THREAD

**Issue by omo50** [ViolaFlower/Re-Console#101]
I need a panorama for 1.21, considering to (most likely) fix #100 I'd have to maintain 2 versions of Re-Console Resources, I think having a 1.21 panorama for the 1.21 version would be kinda helpful.

Please send any if you have them here, that would be appreciated! Thanks

**Comment by Cjnator38** [comment]
![panorama_day](https://github.com/user-attachments/assets/38cae2ca-b4d5-4661-9fd2-8df4e06cc756)
![panorama_night](https://github.com/user-attachments/assets/073dae5c-b15f-4bc8-9320-1fda78a30a50)
had these made shortly after the official panorama dropped, and right before I made the current 1.20 panorama

**Comment by omo50** [comment]
> 
> ![panorama_day](https://github.com/user-attachments/assets/38cae2ca-b4d5-4661-9fd2-8df4e06cc756)
> ![panorama_night](https://github.com/user-attachments/assets/073dae5c-b15f-4bc8-9320-1fda78a30a50)
> had these made shortly after the official panorama dropped, and right before I made the current 1.20 panorama

Thanks!

**Comment by Wilyicaro** [comment]
nice panorama

**Comment by contrarybaton60** [comment]
it's very nice indeed, if only i had one
