### ISSUE TITLE
XBox 3rd party controller issue with natives

### ISSUE THREAD

**Issue by Easyidle123** [ViolaFlower/Re-Console#106]
When using 0.7.0 of re-console for 1.21 with legacy4j, natives do not work for my 3rd party controller in that buttons do nothing. The cursor moves (seemingly windows input), but buttons otherwise won't respond. Holding a button while moving the cursor slows it down significantly for some reason.
GFLW does work somewhat, but will double input when pressing A as windows is also registering it as a click. 

Notably, **the same issues do not occur on a fresh install of legacy4j, of the same version**. This implies that the issue is with re-console specifically.

**Comment by omo50** [comment]
can you just like, check if your controller is bound correctly?? theres no reason this would be a reconsole issue

**Comment by Easyidle123** [comment]
I've checked pretty thoroughly, still having the issue and it should all be bound correctly. The controller is even detected, but not giving any input. I'm also having the issue on a newly created pack with just Legacy4j (but not an existing one with the same mod version?), so seems this is indeed not a Re-Console issue, likely something convoluted but on my end. I'll create a ticket there instead if/when I track down what's causing it.

**Comment by omo50** [comment]
If you could reproduce with Legacy4J, it's their problem, not mine.
