### ISSUE TITLE
Giant Chat Chat Message when in servers

### ISSUE THREAD

**Issue by ResistVR** [ViolaFlower/Re-Console#108]
![2024-07-27_19 03 18](https://github.com/user-attachments/assets/1eac31e1-1dd3-4483-b42b-8e1c0c5ace27)

**Comment by omo50** [comment]
can you reproduce with just legacy4j installed

**Comment by JuniperIsSleepy** [comment]
you joined a Beta server, there is nothing omo can do about that

**Comment by omo50** [comment]
> you joined a Beta server, there is nothing omo can do about that

LOL???????? Please dont report any issues with a modified version of Re-Console, i will not support it

**Comment by omo50** [comment]
@JuniperIsSleepy thanks for saving me a headache with saying that 😭

**Comment by JuniperIsSleepy** [comment]
> @JuniperIsSleepy thanks for saving me a headache with saying that 😭

yeah its a thing when l4j and viafabric i believe
