### ISSUE TITLE
Suggestion regarding replication of old combat and smaller console edition details.

### ISSUE THREAD

**Issue by JuniperIsSleepy** [ViolaFlower/Re-Console#109]
Instead of using Old Combat Mod, I recommend using the NostalgicTweaks mod with these settings.
[nostalgic_tweaks.json](https://github.com/user-attachments/files/16401555/nostalgic_tweaks.json)
I have tweaked combat to be as close to the latest version of Legacy Console Edition as possible, including particles and sounds. I have also tweaked a select few other details such as a square chunk distance and reduced swaying of the hand.

Another small mod you can optionally include is "Keep Doors Closed" as it fixes an issue where villagers will leave their doors open behind them most of the time.

**Comment by JuniperIsSleepy** [comment]
Actually, in NT, remember to turn off the list of full block selection outlines, i forgot to turn that off

**Comment by omo50** [comment]
Doesn't NT break server compatibility with stuff like Hypixel? Or risk a ban or something like that? Currently the only mod with a risk in RC is Legacy4J

**Comment by JuniperIsSleepy** [comment]
That might be true. Though, we already told people not to use it on servers anyways. I feel like Nt had a server side only option somewhere.

**Comment by JuniperIsSleepy** [comment]
> That might be true. Though, we already told people not to use it on servers anyways. I feel like Nt had a server side only option somewhere.

it does not it seems

**Comment by omo50** [comment]
> > That might be true. Though, we already told people not to use it on servers anyways. I feel like Nt had a server side only option somewhere.
> 
> it does not it seems

Interesting. I'll look into wether this is worth it or not
My only worry is porting to new versions, if NT takes a long time I'd like re-console to not be stuck

**Comment by omo50** [comment]
I might post a test build for it on here eventually. May be a good thing for 0.7.1 which will have beta builds up most likely tomorrow

**Comment by JuniperIsSleepy** [comment]
I understand. I checked and the changes that change combat are server side only, and the changes i made to the client are purely aesthetic.

**Comment by omo50** [comment]
Although there is a problem due to the fact 1.20.1 is also supported, which runs a wildly different NT version due to how Adrenix rewrote the mod for like 10 months

I'd like for there to be as much parity as possible between the versions, and to my knowledge NT Beta 9 isnt being backported to 1.20.1?

**Comment by JuniperIsSleepy** [comment]
While it isn't announced on github, surprisingly Adrenix is backporting it to 1.20.1 from what I've heard. No idea on an eta on that. the main advantage of NT is granular control over mechanics, particles and sounds which let me remove the sweep completely.

**Comment by omo50** [comment]
Yeah, I get that. This may just be out of the question until said backport is done due to the differences in versions though. I'm open for it to be added once that's done though :3

**Comment by omo50** [comment]
Ill likely release a beta build for 1.21 with the mod if I can sometime this week. I'm sorta busy at the moment so I may not have time though. Most likely will not be added until Beta 9 is backported to 1.20.1 out of me wanting to have parity between the two (to stop complaining from people)

**Comment by omo50** [comment]
Aaand i just checked Modrinth and it's backported.

I'll add it to 0.7.1, thanks for the suggestion
