### ISSUE TITLE
Axes does more damage than sword, making swords useless.

### ISSUE THREAD

**Issue by GustavoJadson** [ViolaFlower/Re-Console#110]
In the latest 1.21 release, the axes does more damage than the sword. As the coldown is removed, the weapons damage are not rebalanced.

**Comment by JuniperIsSleepy** [comment]
I must have accidentally unticked old damage values toggle.

**Comment by omo50** [comment]
ill fix this in 0.7.2 tomorrow

**Comment by GustavoJadson** [comment]
Thank you! Are you planning on removing the sweeping edge effect, or making it enchantment only?

**Comment by JuniperIsSleepy** [comment]
wait i just tested on a fresh instance and this isnt the case at all

**Comment by JuniperIsSleepy** [comment]
[nostalgic_tweaks.json](https://github.com/user-attachments/files/16421685/nostalgic_tweaks.json)
also heres the new config all i did was disable the full block selection outlines that were on for some reason

**Comment by omo50** [comment]
> [nostalgic_tweaks.json](https://github.com/user-attachments/files/16421685/nostalgic_tweaks.json) also heres the new config all i did was disable the full block selection outlines that were on for some reason

I had thought i had disabled that? Either way, thanks, I appreciate it

**Comment by omo50** [comment]
fixed in 0.7.2
