### ISSUE TITLE
[Bug]: Sharpness doesn't work

### ISSUE THREAD

**Issue by Youseffo13** [ViolaFlower/Re-Console#112]
### What is the issue?

With the new update of reconsole the enchantment sharpness doesn't work anymore

Ex. The diamond sword does 7 of damage. Even with sharpness 5 does the same amount of damage

### To Reproduce

You need to enchant the sword with sharpness

### Minecraft Version

1.21

### Re-Console Version

0.72

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment]
ill look into this

**Comment by omo50** [comment]
this is just a visual error regarding tooltips. I tested damage values and an unenchanted sword takes 3 hits to kill a creeper. a sharp 5 sword takes 2. I'll look into a fix for a later version, unlikely to be in 0.7.3 though

**Comment by bugsbugsbugsLCE** [comment]
This is not a bug with legacy4j but a bug by the vanilla game. When mojang made enchantments data driven they just added a minecraft:damage function to the enchantment instead of modifying the attack damage attribute like it used to be. Mojang will probably eventually fix this.
