### ISSUE TITLE
[Bug]: trying to 

### ISSUE THREAD

**Issue by jazziejazzgirl** [ViolaFlower/Re-Console#113]
### What is the issue?

cannot type properly in book and quill

### To Reproduce

1. get book and quill item
2. typing the spacebar keeps opening up the keyboard screen. i dont know how to turn this off if its even an option
3. can't type normally

also i cant sign my name when im finished, i have to press tab three times to be able to do it?

### Minecraft Version

1.21

### Re-Console Version

0.7.2

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by DBTDerpbox** [comment]
I could be wrong, but this looks way more like a legacy4j issue instead of a reconsole issue

**Comment by omo50** [comment]
Next time give your issue an actual name.

Can you reproduce with just Legacy4J? This is most likely an issue on their end

**Comment by jazziejazzgirl** [comment]
> name.
> 
> Can you reproduce with just Legacy4J? This is most likely an issue on their end

sorry i messed the name up im new to github im only here to rlly ask for questions n stuff :p

**Comment by jazziejazzgirl** [comment]
yes i tried with just legacy4j and it did it then

**Comment by omo50** [comment]
then submit it to their repo, this isnt anything on my end
