### ISSUE TITLE
[Bug]: Selecting sliders doesn't change background color

### ISSUE THREAD

**Issue by malkXp** [ViolaFlower/Re-Console#114]
### What is the issue?

When you select a slider in the options, the slider's background color stays the same

### To Reproduce

1. Go to options menu
2. Go to any submenu with sliders (I went to User Interface)
3. Hover over a Slider (This bug happens with Force Yellow Text and Without it)

This is what the bug looks like
![image](https://github.com/user-attachments/assets/04497dcf-ded4-4f26-8066-6064105803ed)

This is what the slider Should look like
![image](https://github.com/user-attachments/assets/5229484a-14a0-4326-8999-61fad4acc4ea)

### Minecraft Version

1.21

### Re-Console Version

0.7.2+mc1.21

### Additional Context

This is relatively a small bug but the sliders can really only be seen if you have Force Yellow Text on, else the slider selection will be really hard to see.

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment]
can you repro with just legacy4j

**Comment by JuniperIsSleepy** [comment]
This is working as intended, as yellow text and white outlines are the default. Turn on Programmer Art to re-add the original style. The original is being made the default next update for L4J thanks to a Poll by Wily.

**Comment by omo50** [comment]
> This is working as intended, as white text and white outlines are the default. Turn on Programmer Art to re-add the original style. The original is being made the default next update for L4J thanks to a Poll by Wily.

i see
