### ISSUE TITLE
0.7.4 things and feedback ig

### ISSUE THREAD

**Issue by omo50** [ViolaFlower/Re-Console#116]
### What would you like added?

ummm haii 
- add https://modrinth.com/resourcepack/default-dark-mode-expansion (idk it seems cool)
- separate tutorial worlds from reconsole resources to allow ppl to disable them if they don't like the more cluttered ui (will be uploaded to modrinth so others can include it in modpacks!)
- add https://modrinth.com/mod/betterf3 (more human readable and customizable)

I'd also like to note that suggestions are now hosted on this repository, as that way I can actually see them!

There will be more to this update when I'm back from my trip, but I've been focusing a lot on customizability since the addition of NT. I think it's cool

### What should be done about this?

read the thing above

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment]
Also thank you all for 300+ followers and 90k on Modrinth! It really does mean a lot to me. Here's to 100k!

**Comment by Rykst3r** [comment]
## What would you like added?
If possible, I think it'd be cool to have an option to create finite worlds similar to that of the Legacy Console Editions and old Pocket Editions. A bit of a strange suggestion, I know. Considering that infinite worlds are insanely better. But I get a lot of nostalgia for the limited world sizes I played with on Pocket Edition 0.7.1 Alpha and the PlayStation 3 Edition.

## Is your feature request related to a problem?
Not really.

## What should be done about this?
Just take it into consideration. It isn't a NECESSARY feature, but something I think would be nice to have.

## Additional Context
https://minecraft.wiki/w/Legacy_Console_Edition_exclusive_features#World_generation

## Acknowledgement
 I understand and have fully filled out the form.

**Comment by omo50** [comment]
> ## What would you like added?
> If possible, I think it'd be cool to have an option to create finite worlds similar to that of the Legacy Console Editions and old Pocket Editions. A bit of a strange suggestion, I know. Considering that infinite worlds are insanely better. But I get a lot of nostalgia for the limited world sizes I played with on Pocket Edition 0.7.1 Alpha and the PlayStation 3 Edition.
> 
> ## Is your feature request related to a problem?
> Not really.
> 
> ## What should be done about this?
> Just take it into consideration. It isn't a NECESSARY feature, but something I think would be nice to have.
> 
> ## Additional Context
> https://minecraft.wiki/w/Legacy_Console_Edition_exclusive_features#World_generation
> 
> ## Acknowledgement
> I understand and have fully filled out the form.

Theoretically in the future I could try and port a form of limited world generation into a datapack format that you can use. Not for this update though but it has been considered

**Comment by omo50** [comment]
1.21.1 support i guess too
