### ISSUE TITLE
only old music 

### ISSUE THREAD

**Issue by Coolldudeabc123** [ViolaFlower/Re-Console#118]
### What would you like added?

is there any way where you can make it to where only the old music plays from the console edition so basically all music before update aquatic if you could add this that would be great 

### What should be done about this?

I would like there to be an option for only the old music 

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment]
you can use a resource pack or something

**Comment by JuniperIsSleepy** [comment]
open nostalgictweaks configuration by pressing "o" and go to sound > game music and configure there.
