### ISSUE TITLE
[Bug]: The camera swerves too far when turning corners on a minecart.

### ISSUE THREAD

**Issue by tomopoms** [ViolaFlower/Re-Console#119]
### What is the issue?

When riding in a minecart and turning a corner, the camera will turn twice as much, and you will be looking off to the side instead of straight ahead. And after two of the same turns, you will be facing backwards.

### To Reproduce

Hop into a minecart and ride it on a rail with a turn. I found this out while playing in the tutorial worlds.

### Minecraft Version

1.21

### Re-Console Version

0.7.3+mc1.21

### Additional Context

I was not able to recreate this bug in just Legacy4J, only in Re-Console.

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by JuniperIsSleepy** [comment]
I know why this is actually but i forgot to report it. Turn off minecart turning in nostalgictweaks configuration (press “o” to open the config and go to game mechanics -> minecart)

@omo fix this in next update

**Comment by omo50** [comment]
will be fixed in next update

don't @ me for stuff though this woke me up at 1 am bc of a notification and I have 14 hrs - of travel tomorrow, I'll see it eventually anyway

**Comment by JuniperIsSleepy** [comment]
oh sorry i didnt know you get notifications from that
