### ISSUE TITLE
[Bug]: Some items is not rendering properly in hotbar

### ISSUE THREAD

**Issue by Ivanoshechka** [ViolaFlower/Re-Console#120]
### What is the issue?

Issuse with hotbar when he is lower 100% of opacity.

### To Reproduce

1. Download lastet re-cosnole.
2. Make sure that's opacity is lower than 100%.
3. Log in random world.
4. Pick Grass block or Short Grass or Oak leaves. 

### Minecraft Version

1.21.1

### Re-Console Version

0.7.4-1.21.1

### Log

[latest.log](https://github.com/user-attachments/files/16604282/latest.log)

### Additional Context

![image](https://github.com/user-attachments/assets/16dd972f-021b-48d9-bf2c-225eaa3ba184)

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment]
noted. working on an attempt for a fix rn

**Comment by omo50** [comment]
fixed in 0.7.5. Weirdly an issue with Moderner Beta?? Im very confused, but it is fixed

**Comment by Ivanoshechka** [comment]
No way.

**Comment by omo50** [comment]
> No way.

yeah, confused me a lot. immediatelyfast caused a similar issue regarding darker items in the hotbar, but it didnt fix the invisible items in my tests until i removed moderner beta

idk how i didnt catch this originally 😭 ill test a lot more from now on
