### ISSUE TITLE
Switch Pro Controller Suport

### ISSUE THREAD

**Issue by ForestMinecraft** [ViolaFlower/Re-Console#121]
### What would you like added?

A setting that swaps the X and Y buttons. 

### What should be done about this?

Add a setting to swap X and Y buttons.

### Additional Context

Switch pro controllers have the locations of the X and Y buttons swapped along with the A and B buttons.

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment]
thats something for legacy4j to do, not me

**Comment by JuniperIsSleepy** [comment]
its in controller options near the top
