### ISSUE TITLE
[Bug]: Game crashes after inital "Ok" popup mesage. (Fabric, 1.21.1, Prism Launcher)

### ISSUE THREAD

**Issue by blockplace1232** [ViolaFlower/Re-Console#124]
### What is the issue?

The game crashes after clicking the "Ok" box after getting past the logos

### To Reproduce

Step 1. Start the game through prism launcher and wait for the game to get past the title screen.

Step 2. Click and wait for the white square circle to finish spinning. 

Step 3. Click "OK" on the inital text box.

Step 4. Game crashes and exits with code "255" and the crash log.

### Minecraft Version

1.21

### Re-Console Version

0.7.11+mc1.21.1+fabric 

### Log

Pastebin link here because character maximum limit was reached: https://pastebin.com/KpPd6ZqE

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment]
You're on an outdated version. Play on 0.7.10 or 0.8.0.beta.2

**Comment by blockplace1232** [comment]
Bro im using 0.7.11 not 0.7.10

**Comment by blockplace1232** [comment]
look its literally on the re-console page on modrinth as the latest stable version i downloaded it a minute ago

Look here: https://cdn.modrinth.com/data/g9O0WaGR/versions/ED5bNbWD/Re-Console%200.7.11%2Bmc1.21.1%2Bfabric.mrpack

**Comment by Permdog99** [comment]
I can confirm that this happens on 0.7.11 fairly easily. Downloaded Re-Console on Modrinth just now and it crashes. Nostalgic Tweaks is not designed for 1.21.1 and the latest version (Beta 904) is not compatible with Legacy4J. I would suggest downgrading to 902 or 903.

**Comment by omo50** [comment]
> I can confirm that this happens on 0.7.11 fairly easily. Downloaded Re-Console on Modrinth just now and it crashes. Nostalgic Tweaks is not designed for 1.21.1 and the latest version (Beta 904) is not compatible with Legacy4J. I would suggest downgrading to 902 or 903.

the 0.8 betas are the ones currently intended to be used, not the 0.7.11 builds. The difference between 1.21.1 and 1.21 are critical server fixes which don't impact **most** mods, including NT

**Comment by omo50** [comment]
> Bro im using 0.7.11 not 0.7.10
You must have misread my message; I said play on 0.7.10 or the 0.8.0 beta

**Comment by omo50** [comment]
The issue that 0.7.11 has is a glitch with the Modrinth App, which since that's happened I've moved to prism for development. I plan on fixing 0.7.11 and releasing .12 as an alternative to the 0.8 builds
