### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by JackxnIsntFunny** [ViolaFlower/Re-Console#125]
### What is the issue?

Chest opening animation still shows the closed chest model

### To Reproduce

1: Open a chest

### Minecraft Version

1.21

### Re-Console Version

0.8.0-beta2

### Log

[latest.log](https://github.com/user-attachments/files/16740754/latest.log)

### Additional Context

This screenshot below shows what i saw.
![2024-08-25_10 49 37](https://github.com/user-attachments/assets/d5695d03-7198-4ae6-809b-dad2a955e8a4)
(NOTE: Tick rate was adjusted just to show what happens when you open a chest.)

### Acknowledgement

- [x] I understand and have fully filled out the form.

**Comment by omo50** [comment]
can you try disabling ImmediatelyFast

**Comment by omo50** [comment]
ill look into this for beta 5

**Comment by omo50** [comment]
fixed
