### ISSUE TITLE
[Bug]: composter is not in the crafting menu

### ISSUE THREAD

**Issue by greatinternetmachine** [ViolaFlower/Re-Console#126]
### What is the issue?

composter does not show up in the crafting menu

### To Reproduce

1. open crafting menu
2. composter is nowhere to be found

### Minecraft Version

1.21

### Re-Console Version

0.7.10 mc1.21.1

### Log

[latest.log](https://github.com/user-attachments/files/16741499/latest.log)

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by DBTDerpbox** [comment]
this might be a legacy4j issue and not reconsole, I'll double check when I can

**Comment by omo50** [comment]
^ This would be a problem to report to the Legacy4J repository if it is infact missing. Can't check currently but that'd be on their end if it is gone, not ours
