### ISSUE TITLE
[Bug]: MidnightLib causes game to not render/freeze on startup

### ISSUE THREAD

**Issue by Jab125** [ViolaFlower/Re-Console#130]
### What is the issue?

Game either black screens (without Sodium) or freezes on the 4J Studios logo

### To Reproduce

Start the game

### Minecraft Version

1.21

### Re-Console Version

0.8.0.beta.5+mc1.21.1+fabric

### Log

https://gist.github.com/Jab125/8f30b3005253b90c0e7b14883f5e34f7

### Additional Context

OS: macOS 14.2 Sonoma
Chip: Apple M2
Device: Mac Mini 2023

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment]
will fix later, thanks 👍

**Comment by omo50** [comment]
fixed
