### ISSUE TITLE
[Bug]: The game randomly crash

### ISSUE THREAD

**Issue by zozogame1** [ViolaFlower/Re-Console#131]
### What is the issue?

Game crashes

### To Reproduce

There is no specific step to do because it can crash at any moment (in-game or in the menu).

### Minecraft Version

1.21

### Re-Console Version

0.8.0 Beta 5 for 1.21.1 for Fabric

### Log

[hs_err_pid7752.log](https://github.com/user-attachments/files/16837643/hs_err_pid7752.log)

### Additional Context

I'm using Prism Launcher, with java 21.0.4, minimum 512 mb of ram and maximum 2650 mb of ram.
I'm using Windows 10 22H2 19045.4842 (Beta channel, but the crash happened before I switched to the beta channel if I remember correctly), an Intel(R) Pentium(R) CPU 5405U @ 2.30GHz, 2304 MHz, 4G of RAM and an Intel UHD Graphics 610.

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment]
this seems more like an error with your system in specific, rather than an issue with reconsole

**Comment by zozogame1** [comment]
Do you have any idea of what it could be ?

**Comment by omo50** [comment]
you can try reinstalling java
