### ISSUE TITLE
[Bug]: Crashing after pressing ok (0.7.11-fabric 1.20.1 "release") 

### ISSUE THREAD

**Issue by devingDev** [ViolaFlower/Re-Console#132]
### What is the issue?

The game crashes instantly if I press the OK button at the start screen.

### To Reproduce

LOGS: https://mclo.gs/gmd1xTT

I was trying to figure out which version to use and has the most complete mod set. According to the main page and literally just downloading a few versions it seemed 0.7.11 1.20.1 had the most.
Mainly "Nostalgic Tweaks" seemed interesting in that.

But it crashes once I press ok in the start screen.

What's the preferred version to use? Is it always the latest even if it says beta?

### Minecraft Version

1.21

### Re-Console Version

0.7.11 Fabric

### Log

https://mclo.gs/gmd1xTT

[log_mc.txt](https://github.com/user-attachments/files/16846872/log_mc.txt)

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment]
you can play on the 0.8 beta's, although they may have some slight amount more problems, it should be fine. The most complete version for you would probably be 0.7.12.

0.7.11 is broken and I'm not going to patch an old version
