### ISSUE TITLE
[Bug]: Upgrading from major releases (for example 0.7.x -> 0.8.0) resets "options.txt"

### ISSUE THREAD

**Issue by kaer1a** [ViolaFlower/Re-Console#133]
### What is the issue?

When updating (beta & stable/release) to major updates resets "options.txt"

### To Reproduce

1 - install the latest stable re-console versions
2 - config something in game in the in game options
3 - update to 0.8.0 
4 - options.txt is reset 

### Minecraft Version

1.21

### Re-Console Version

i am currently on 0.8.0 beta 3

### Log

i have no log to upload for this issue lmao

### Additional Context

even when updating from beta 3 to beta 4 or 5 reset my "options.txt"

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment]
fixed (hopefully)

**Comment by Cjnator38** [comment]
still occurs when updating from beta 9 -> 10

**Comment by omo50** [comment]
was informed by skye. will look at for beta 11

**Comment by omo50** [comment]
ok so im stupid its bc ive been including the options.txt in the export  even when it was in the yosbr folder
will be fixed next version 😭
