### ISSUE TITLE
Remove offset given by Chat Heads

### ISSUE THREAD

**Issue by Cjnator38** [ViolaFlower/Re-Console#135]
### What would you like added?

Now that Legacy4J moves the chat into the "safe zone", the chat offset given by Chat Heads for non-player messages should probably be disabled to reduce the gap from the left side of the screen
![2024-09-04_22 59 38](https://github.com/user-attachments/assets/a967ed7b-c4f3-44df-ad21-c973093c9a76)
![2024-09-04_22 59 19](https://github.com/user-attachments/assets/af76c4d9-10aa-4229-9fb5-4b50a0bf04df)

### What should be done about this?

Disable "Offset non-player text chat" in the Chat Heads config

### Additional Context

small tiny miniscule microscopic atomic ultra minor feature change request thingy :)

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment]
yea sure

**Comment by omo50** [comment]
implemented
