### ISSUE TITLE
Move Resource Assorts to YOSBR

### ISSUE THREAD

**Issue by Cjnator38** [ViolaFlower/Re-Console#138]
### What would you like added?

Resource Assorts that are provided or modified by Re-Console should be handled by YOSBR and not the mrpack. This would be done so any personal modifications to these assorts would be saved through updates.

### What should be done about this?

Move `*.mrpack/overrides/resource_assorts/` to `*.mrpack/overrides/config/yosbr/resource_assorts/`.

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment]
implemented
