### ISSUE TITLE
Add Hot-Join and TwinSession for split-screen support!

### ISSUE THREAD

**Issue by imheavi** [ViolaFlower/Re-Console#140]
### What would you like added?

The Hot-Join and TwinSession mods to be added, which allows for split-screen and joining with the same account twice.

### Is your feature request related to a problem?

No.

### What should be done about this?

Add the mods!

### Additional Context

Links to the aforementioned mods are here:

https://modrinth.com/mod/hotjoin
https://modrinth.com/mod/twinsession

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment]
added
