### ISSUE TITLE
Add mod-only options in a misc. thingy

### ISSUE THREAD

**Issue by Pacomatic1** [ViolaFlower/Re-Console#141]
### What would you like added?

There are some mod-specific stuffs only accessible via keybinds - Iris, Resolution Control etc.
I want to access them through a menu.

### What should be done about this?

I think we should access them through the settings menu, or putting them in places where they belong.
For example, put Iris and Resolution Control in the Video Settings and put Nostalgic Tweaks and CraftPrescence in the game settings. 
This is good for people playing on Controller or who don't like having a bajillion keybinds just for menus.

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment]
this would be for legacy4j, not me
