### ISSUE TITLE
install guide??

### ISSUE THREAD

**Issue by Sanic9kvr** [ViolaFlower/Re-Console#144]
### What would you like added?

an install .txt

### Is your feature request related to a problem?

I have no idea how to install it

### What should be done about this?

A way so it can be easily installed

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by LewisTheGithubber** [comment]
Install it with a launcher like curseforge, modrinth, or prismlauncher. Modrinth would be the easiest to set up

**Comment by DBTDerpbox** [comment]
Its a Modpack, use something like Modrinth or PrismLauncher.

**Comment by omo50** [comment]
https://github.com/ViolaFlower/Re-Console/wiki/Installation
