### ISSUE TITLE
[Bug]: I can't download Re-Console using Modrinth Pack to Zip Converter, I download it, the bar is full but it doesn't download and performance gets worse

### ISSUE THREAD

**Issue by Eliassxd** [ViolaFlower/Re-Console#146]
### What is the issue?

I can't download Re-Console using Modrinth Pack to Zip Converter

### To Reproduce

Copy the Re-Console modpack ID, go to Modrinth Pack to Zip Converter and download

### Minecraft Version

1.21

### Re-Console Version

1.21.1 But since I can't download it I don't know much

### Log

Can't

### Additional Context

I just want to play Re-Console :(

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment]
I do not support unofficial methods of installing Re-Console, whether that be changing the file format or piracy. I recommend reading https://github.com/ViolaFlower/Re-Console/wiki/Installation for info on how to install.
