### ISSUE TITLE
[Bug]: custom tutorial+extra rescources dont load???

### ISSUE THREAD

**Issue by kitkat390** [ViolaFlower/Re-Console#148]
### What is the issue?

tutorial worlds and the custom resource packs dont load

### To Reproduce

i pput my java file and the zip into mods folder (in the LL files) and they dont load. only l4j

### Minecraft Version

1.21

### Re-Console Version

latest

### Additional Context

i use LL because i dont have any money for mc, i do plan on buying it in the future so dont get all upset because of it. i know some people would

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment]
Pirated Minecraft is not supported
