### ISSUE TITLE
[Bug]: fullscreen kinda broken

### ISSUE THREAD

**Issue by CimkNoYAP** [ViolaFlower/Re-Console#149]
### What is the issue?

so fullscreen is doing it but it doesnt hide the taskbar. 

### To Reproduce

i dont know. when i first started. i changed nothing. and its like that.

### Minecraft Version

1.21

### Re-Console Version

0.8.2

### Log

[latest.log](https://github.com/user-attachments/files/17803460/latest.log)

### Additional Context

im on windows 10. im on a 1920x1080 monitor. with a RTX 3070 8gb
and a i7 4770K processor. with 24 gigs of ddr3 ram. if you need another thing. please ask.

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by CimkNoYAP** [comment]
![image](https://github.com/user-attachments/assets/4da7df87-3700-4f47-bc57-667cd9a7e5f3)
this is the screen shot. no matter if i exit fullscreen and enter it again. it doesnt fix it.

**Comment by omo50** [comment]
mod menu>concentration to disable

**Comment by CimkNoYAP** [comment]
thank you!!!
