### ISSUE TITLE
Performance degredation in split-screen compared to base Legacy4J?

### ISSUE THREAD

**Issue by Meepster-836** [ViolaFlower/Re-Console#150]
### What is the issue?

Splitscreen performance is much lower in Re-Console compared to Legacy 4J + basic mods

### To Reproduce

Create an instance with just Legacy4J + a few basic mods (sodium, lithium, modernfix, ferritecore, and krypton) + a mod for splitscreen if applicable (nucleus coop may work too, but I am not on windows so I can't use that). Performance should be good.

Run a 4-player game. Observe performance (you may want to uncap framerate)

Run a 4-player game inside of a Re-Console instance. Observe performance. It may be much lower.

### Minecraft Version

1.21

### Re-Console Version

0.8.0 Beta 14

### Additional Context

Some context: There was a post a while back where someone ran 8-player splitscreen minecraft on a Steam Deck, running flawlessly at at least 1440p60 (may have even been 4k) and on Windows.

I was inspired by that and attempted to do something similar on my Steam Deck using Re-console after it gained split-screen capability.
To get it to work at all I did have to _manually update Hot-Join_ to 4.0.
The performance however, was terrible. I was running in 720p and getting a low, stuttery framerate.

To try and get closer to the cause of the problem I created a 1.20.1 instance (couldn't get 1.21.1 to work with hot-join for some reason) and installed just legacy4J + sodium, lithium, modernfix, ferritecore, and krypton. I also used the "Splitscreen Support" mod instead of hot-join as it was not available on 1.20.1.

There it performed much, much better. I got a smooth 60, just like the post. I tried to see if it was Hot-Join causing the performance issue in Re-Console, but "Splitscreen Support" isn't on 1.21.1 for me to have an alternate splitscreen method, and Hot-Join isn't on 1.20.1. And as stated earlier, Hot-Join refused to work on 1.21.1 with basically just it's dependencies + legacy4j, so I was unable to see if Hot-Join was the culprit.

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by S-N00B-1** [comment]
Have you considered, that running 4 instances of the game, with mods, might degrade performance?

**Comment by omo50** [comment]
along with what Snoob said, you are also running an outdated version of Re-Console. You should not be reporting issues that are due to the fact you are literally running 4 separate versions of minecraft.

**Comment by omo50** [comment]
along with what Snoob said, you are also running an outdated version of Re-Console. You should not be reporting issues that are due to the fact you are literally running 4 separate versions of minecraft.

**Comment by Meepster-836** [comment]
I have considered that, yes. The thing that bothers me is how drastic the fall-off is, for what Re-Console does on top of L4J.

On top of that, I also was setting up another instance with a modpack I had to see how well splitscreen worked there. The performance was still great like the basic instance, with terralith, tectonic, create, and more. I even was running at 12 render distance on the basic/modpack instance compared to 6 on Re-Console.

**Comment by omo50** [comment]
I do doubt the issue is with Re-Console specifically. This is not something i am going to fix

**Comment by omo50** [comment]
You are also trying to run this on a steam deck.

**Comment by Permdog99** [comment]
> I have considered that, yes. The thing that bothers me is how drastic the fall-off is, for what Re-Console does on top of L4J.
> 
> On top of that, I also was setting up another instance with a modpack I had to see how well splitscreen worked there. The performance was still great like the basic instance, with terralith, tectonic, create, and more. I even was running at 12 render distance on the basic/modpack instance compared to 6 on Re-Console.

Was this other modpack using L4J? L4J destroys performance by a lot of you aren't using performance mods.

Also could you make a new instance that is running 1.21.1 and see if L4J + the mods you had in the 1.20.1 instance + hot join? Then try again? I have a feeling the performance issues may be because of hot join

**Comment by Meepster-836** [comment]
> You are also trying to run this on a steam deck.

In the main post I mentioned there was a reddit post where someone ran 8-player minecraft on a steam deck and it ran flawlessly. I do think the steam deck is more capable than you're giving it credit for.

I will concede that it's probably not a Re-Console _specific_ issue though, and I probably should have looked somewhere else to figure this out.

**Comment by Meepster-836** [comment]
> Was this other modpack using L4J? L4J destroys performance by a lot of you aren't using performance mods.
> 
> Also could you make a new instance that is running 1.21.1 and see if L4J + the mods you had in the 1.20.1 instance + hot join? Then try again? I have a feeling the performance issues may be because of hot join

I had tried to isolate hot-join, but I couldn't get it working on a basic 1.21.1 instance despite having all of it's dependencies, including l4j. I tried to do it the other way and use the alternate splitscreen mod on 1.21.1 but it is only on 1.21.0 right now.
As for the modpack, I believe some of the things on there are only available on 1.20.1.

**Comment by omo50** [comment]
> > Was this other modpack using L4J? L4J destroys performance by a lot of you aren't using performance mods.
> > Also could you make a new instance that is running 1.21.1 and see if L4J + the mods you had in the 1.20.1 instance + hot join? Then try again? I have a feeling the performance issues may be because of hot join
> 
> I had tried to isolate hot-join, but I couldn't get it working on a basic 1.21.1 instance despite having all of it's dependencies, including l4j. I tried to do it the other way and use the alternate splitscreen mod on 1.21.1 but it is only on 1.21.0 right now. As for the modpack, I believe some of the things on there are only available on 1.20.1.
> 
> Oh yeah, and hot join is only available on 1.21.1

1.21.0 and 1.21.1 are functionally the same. just try using a dependency override/

**Comment by Permdog99** [comment]
> > Was this other modpack using L4J? L4J destroys performance by a lot of you aren't using performance mods.
> > Also could you make a new instance that is running 1.21.1 and see if L4J + the mods you had in the 1.20.1 instance + hot join? Then try again? I have a feeling the performance issues may be because of hot join
> 
> I had tried to isolate hot-join, but I couldn't get it working on a basic 1.21.1 instance despite having all of it's dependencies, including l4j. I tried to do it the other way and use the alternate splitscreen mod on 1.21.1 but it is only on 1.21.0 right now. As for the modpack, I believe some of the things on there are only available on 1.20.1.
> 
> Oh yeah, and hot join is only available on 1.21.1

If you can get a 1.21.1 instance with Hot-join working, then let us know the results of the performance

Also are you in gaming mode or desktop mode?

**Comment by Meepster-836** [comment]
> > > Was this other modpack using L4J? L4J destroys performance by a lot of you aren't using performance mods.
> > > Also could you make a new instance that is running 1.21.1 and see if L4J + the mods you had in the 1.20.1 instance + hot join? Then try again? I have a feeling the performance issues may be because of hot join
> > 
> > 
> > I had tried to isolate hot-join, but I couldn't get it working on a basic 1.21.1 instance despite having all of it's dependencies, including l4j. I tried to do it the other way and use the alternate splitscreen mod on 1.21.1 but it is only on 1.21.0 right now. As for the modpack, I believe some of the things on there are only available on 1.20.1.
> > Oh yeah, and hot join is only available on 1.21.1
> 
> If you can get a 1.21.1 instance with Hot-join working, then let us know the results of the performance
> 
> Also are you in gaming mode or desktop mode?

Desktop mode, as in gaming mode the windows will not show at the same time (it only shows one window at a time)
I will try the dependency override and get back to you, just need to set things up again

**Comment by Meepster-836** [comment]
> how much RAM are you allocating to Minecraft?

I believe I'm allocating 2560MB per instance, so it should be about 10/16GB used total (wanted to save some for VRAM since it's an APU). I believe I've gotten away with more on a different instance type though, so i might try to allocate more. I'll probably do that later today when I have the time.
