### ISSUE TITLE
[Bug]: Deprecated performance on 0.8.2 1.21

### ISSUE THREAD

**Issue by FensBK** [ViolaFlower/Re-Console#151]
### What is the issue?

Deprecated performance

### To Reproduce

The modpack is having performance issues on 0.8.2 when using shaders
Here's a comparison betwen 1.20 and 1.21 on the Steam Deck using Complementary Unbound

1.20 much CPU and GPU usage (higher FPS)
![screenshot](https://github.com/user-attachments/assets/7d7bae17-89e4-418f-9c6d-1d6e645f6cc4)

1.21 less CPU and GPU usage (lower FPS)
![screenshot-1](https://github.com/user-attachments/assets/1afe58c4-ccd4-4dd6-a19d-33e4326118b5)

This issue is not exclusive to the Steam Deck, this is also happening on a AMD Ryzen 5600G with a RTX 4060 TI build with 16GB of RAM but at the time I don't have screenshots.

### Minecraft Version

1.21

### Re-Console Version

0.8.2

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment]
![image](https://github.com/user-attachments/assets/879651ad-20df-4217-9383-3f7ed51db498)
I cant manage to reproduce the same performance hit. In my tests, 1.21.1 runs ~17fps worse, but that is well within the margin of error for a Minecraft world like the TU69 tutorial world. There are a lot of moving parts in a world.

I also see that these tests take place in slightly differing situations, especially regarding the time of day, and positioning. To get a reliable benchmark, you need to be in the same place in the same world, and lock the daylight cycle.

**Comment by FensBK** [comment]
Dude come on, its the SAME world, same exactly spot, same situation! I just updated from 1.20 to 1.21

**Comment by omo50** [comment]
As mentioned, the time of day matters a lot as well. I went through and benchmarked the world in nearly the same spot as you, locked at the same time of day. It also depends on what quality you are running the shaders on

**Comment by FensBK** [comment]
This is the same spot, same shaders and settings in another modpack called Legacy Remade and it is running better
![screenshot-2](https://github.com/user-attachments/assets/e96005e6-bd47-4652-b38b-9e28e4ef4704)

**Comment by FensBK** [comment]
Its also 1.21

**Comment by omo50** [comment]
that is clearly not the same spot or settings. Legacy Remade is also a different pack, running a different set of mods.

**Comment by FensBK** [comment]
Okay, here's a different comparison, now between Re-console 0.8.0 beta 14 and 0.8.2 and on a different world and system before you say "Oh it's Steam Deck's fault"
Specs: AMD Ryzen 5600G + RTX 4060 Ti 16GB 3200MHz
Vsync ON

0.8.0 Beta 14 no shaders
![080 no shader](https://github.com/user-attachments/assets/eac3d074-4ac4-47e4-b078-fcfba560b57d)

0.8.0 Beta 14 Bliss shaders
![080 bliss shader](https://github.com/user-attachments/assets/694cb5be-f2ed-4f1d-a104-e6f0f606e609)

0.8.2 no shaders
![082 no shader](https://github.com/user-attachments/assets/2a977d99-55b1-48f8-9a80-779ba45a0e31)

0.8.2 Bliss shaders
![082 bliss shader](https://github.com/user-attachments/assets/3b90236a-4487-467e-a44f-71e5bc949f0e)

0.8.2 Bliss shaders + better f3 interface open
![082 bliss shader + betterf3](https://github.com/user-attachments/assets/f73edcc6-193d-47fd-b1c7-5e6420726a52)

I get constant 60 fps on 0.8.0 but pretty unstable fps on 0.8.2

**Comment by omo50** [comment]
I see

I'll look into this then. Maybe try removing Concentration and seeing what it does?

**Comment by omo50** [comment]
The issue with the task bar is known and will be fixed in the next update, for more info

**Comment by FensBK** [comment]
Removing Concentration forces me to remove hot-join, now with vsync on locks the game on 30FPS

vsync on
![vsync on](https://github.com/user-attachments/assets/52f542f9-4211-4717-b8e3-129ae2186d47)

vsync off
![vsync off](https://github.com/user-attachments/assets/3817ee05-fc93-4031-80d2-4b342c3bafd8)

**Comment by omo50** [comment]
should be fixed in 0.9

**Comment by omo50** [comment]
update to fix this soon, pc had broken down but it works now

**Comment by Fuzzy143** [comment]
sorry but I have the same issue even with 0.8.3
I tested 1.20 and it has more fps than 1.21
![스크린샷 2024-12-23 161020](https://github.com/user-attachments/assets/5bf411e6-320b-4c46-81ae-dbd217f721ce)
