### ISSUE TITLE
Allow for people to force open the vanilla options menu

### ISSUE THREAD

**Issue by ZZaciek** [ViolaFlower/Re-Console#153]
### What would you like added?

Title. Similar to how in Sodium you can press shift+p to open the vanilla menu for visuals.

### Is your feature request related to a problem?

I'm attempting to use resource packs that aren't in the resource assorts section (which is also dumb in my opinion, because I can't open the mash up worlds either), but I can't

### What should be done about this?

Like i said, just a force open for vanilla menus, if what's present doesn't cover the need we have.

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by ZZaciek** [comment]
or better yet, have an easier way to disable resource assorts. This alone is what's causing me the headache and would prefer just to use resource packs.

**Comment by ZZaciek** [comment]
okay you can open the basic menu in the mod menu, but im going to repost my comment because it's really annoying.

**Comment by omo50** [comment]
This would be for Legacy4J, not me
