### ISSUE TITLE
Easy way to be rid of Resource Assorts

### ISSUE THREAD

**Issue by ZZaciek** [ViolaFlower/Re-Console#154]
### What would you like added?

Title

### Is your feature request related to a problem?

Yes, I would like to be able to use my resource packs in the world menu instead of these assorts, which are annoying as all hell.

### What should be done about this?

Make resource packs take priority or something, i dont know.

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment]
Again. This is for Legacy4J, not me. Be sure to open suggestions at the appropriate place

**Comment by Wilyicaro** [comment]
> ### What would you like added?
> Title
> 
> ### Is your feature request related to a problem?
> Yes, I would like to be able to use my resource packs in the world menu instead of these assorts, which are annoying as all hell.
> 
> ### What should be done about this?
> Make resource packs take priority or something, i dont know.
> 
> ### Additional Context
> _No response_
> 
> ### Acknowledgement
> * [x]  I understand and have fully filled out the form.

You can simply modify the used resource assort, by shift-clicking or pressing left controller button in the Resource Assorts widget, so you can apply your resource packs like in vanilla
