### ISSUE TITLE
[Bug]: Detection issue with 2+ controllers

### ISSUE THREAD

**Issue by umbreonben** [ViolaFlower/Re-Console#155]
### What is the issue?

When a single controller is connected, the game detects it and functions properly. However, connecting an additional controller causes the game to fail to recognize any controllers, including the first one. The issue persists until the second controller is disconnected, and the game is restarted. Notably, the controllers function correctly with other software.

### To Reproduce

1. Use MacOS (Sequoia 15.1.1)
2. Download and open "Re-Console 0.8.2 for 1.21.1 Fabric" on Modrinth
3. Connect a single controller — it is detected, and all functionality works as expected
4. Connect a second controller — upon doing so, no controllers are detected, including the first one

### Minecraft Version

1.21

### Re-Console Version

Re-Console 0.8.2

### Additional Context

I tested this with two Switch Pro controllers, a Switch Pro controller paired with an Xbox 360 controller, and a Switch Pro controller paired with Joy-Cons. All of these controllers work properly with other software, even when all are connected simultaneously for multiplayer games.

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment]
This would be something for the legacy4j repo (https://github.com/Wilyicaro/Legacy-Minecraft/issues)
