### ISSUE TITLE
Sign misalignment

### ISSUE THREAD

**Issue by Cjnator38** [ViolaFlower/Re-Console#19]
First screenshot shows Re-Console 0.2.6
Second screenshot shows Legacy4J 1.6.3c (standalone)

Both using Console Aspects and 4JTweaks

![Screenshot_58](https://github.com/Legacy-Union/Re-Console/assets/39870226/7e772804-2282-43ae-bdc6-f3f4a291ac65)
![Screenshot_59](https://github.com/Legacy-Union/Re-Console/assets/39870226/aedcf799-37ff-4ffd-80cd-bd6444057358)

**Comment by omo50** [comment]
Console Aspects isn't intended to be used with ReConsole, may you test without that?

**Comment by Cjnator38** [comment]
It's still an issue without Console Aspects

https://github.com/Legacy-Union/Re-Console/assets/39870226/03422be6-1840-4536-b07a-724952c037bc

**Comment by omo50** [comment]
huh. will look into. Does this happen with just legacy4j, fabric api and architectury api installed? @Cjnator38

**Comment by Cjnator38** [comment]
Nope, it seems to be a Re-Console specific issue

**Comment by omo50** [comment]
try without immediatelyfast?

**Comment by Cjnator38** [comment]
Disabled ImmediatelyFast, still an issue

**Comment by omo50** [comment]
Try disabling Programmer Art Continuation Project

**Comment by Cjnator38** [comment]
Disabling or deleting?

**Comment by omo50** [comment]
disable the resource pack in the resource pack menu

**Comment by Cjnator38** [comment]
The screenshots I sent initially didn't use Programmer Art or PACP

**Comment by omo50** [comment]
im unsure of what is causing the problem then. ill look into it myself sometime this week

**Comment by theminecraftarchitect** [comment]
still present as of 0.3.6

**Comment by Cjnator38** [comment]
I’ll add that this only affects normal signs, but not hanging signs

**Comment by omo50** [comment]
This appears to be fixed as of 0.4.3

![image](https://github.com/Legacy-Union/Re-Console/assets/144749186/9aabe2b7-5eb2-4eab-8b56-c5f7399fd4b5)

**Comment by Cjnator38** [comment]
Issue is now reintroduced with Enhanced Block Entities being readded
EBE on:
![2024-06-07_18 11 17](https://github.com/ViolaFlower/Re-Console/assets/39870226/932b347b-b790-47dd-bfcb-f3f8f98f5bea)

EBE off:
![2024-06-07_18 15 50](https://github.com/ViolaFlower/Re-Console/assets/39870226/e7e09df7-a060-48bc-967d-1a40e6670f02)

**Comment by Cjnator38** [comment]
easy fix would be to turn off render_enhanced_signs in the ebe config

**Comment by omo50** [comment]
> easy fix would be to turn off render_enhanced_signs in the ebe config

@intergrav mind testing if this fixes it
