### ISSUE TITLE
"Disable autosave" and "Exit without saving" not working as intended

### ISSUE THREAD

**Issue by Cjnator38** [ViolaFlower/Re-Console#35]
Disabling autosave in Re-Console, exiting without saving, then relaunching the world shows that player modifications are still saved to an 
extent.

First video shows Re-Console 0.3.3
Second video shows Legacy4J 1.6.3c, latest Architectury and Fabric APIs

https://github.com/Legacy-Union/Re-Console/assets/39870226/b83e0960-62fa-451e-9b5f-7a208b4a78c2

https://github.com/Legacy-Union/Re-Console/assets/39870226/a068137e-2255-4312-a741-abe523c359e5

Here you can see that the player modified chunks remain intact, from an apparent autosave, and the blocks destroyed by the TNT after that autosave remain destroyed. The TNT was removed immediately before this screenshot
![2024-05-16_23 04 35](https://github.com/Legacy-Union/Re-Console/assets/39870226/31808100-168b-4ba8-b902-55e8f5c53e3e)

**Comment by omo50** [comment]
in all likelihood this is a L4J problem, not a Re-Console kne

Exit Without Saving has many issues (including sending you underground), and I can't do anything about auto save.

**Comment by omo50** [comment]
wait

**Comment by omo50** [comment]
I'm stupid, one second I didn't fully read the comment

**Comment by Cjnator38** [comment]
yeah i was experimenting with it and caught the issue on accident, posted it in media chat, and wily pointed out that it has already been tested to not be an issue with l4j

**Comment by omo50** [comment]
I'm.. actually completely unsure of the problem regarding auto save then. I can't do anything about the Exit Without Saving issue (to my knowledge). Will leave this open as a way to track

**Comment by Wilyicaro** [comment]
> in all likelihood this is a L4J problem, not a Re-Console kne
> 
> Exit Without Saving has many issues (including sending you underground), and I can't do anything about auto save.

This problem of spawning "underground" I believe has not been resolved, because in fact, it is not something that makes any sense what a person expects to happen if you create a world without autosaving and leave the world without saving (the world in LE would be excluded, but I believe it's not currently in Legacy4J)

**Comment by omo50** [comment]
Is this still occuring in 0.5.1? I would like to look into this sometime soon

I'm unsure of what I can exactly do about this, but it may be due to (based on assumptions) Faster Random or C2ME? Very uncertain though

**Comment by Cjnator38** [comment]
Still occurs on 0.5.1

**Comment by Cjnator38** [comment]
Does NOT occur with both mods disabled

**Comment by Cjnator38** [comment]
100% seems to be an issue with C2ME. With Faster Random disabled and C2ME enabled, the issue continues. But with Faster Random enabled and C2ME disabled, the issue is gone.

**Comment by omo50** [comment]
> 100% seems to be an issue with C2ME. With Faster Random disabled and C2ME enabled, the issue continues. But with Faster Random enabled and C2ME disabled, the issue is gone.

going to look into this today :3

**Comment by omo50** [comment]
This should be fixed by [dc4660d](https://github.com/ViolaFlower/Re-Console/commit/dc4660dd31c881e13a8399821e48958b5f2e7d3d)
