### ISSUE TITLE
Killing the Ender Dragon Does Not Cause Explosion Sound

### ISSUE THREAD

**Issue by theminecraftarchitect** [ViolaFlower/Re-Console#56]
After killing the ender dragon, the 'explosion' sound seems to be missing. All sounds are turned on in game settings.

**Comment by theminecraftarchitect** [comment]
Reproduced 2x, it may be the advancement sound overriding the explosion sound

**Comment by omo50** [comment]
I'll look into this soon

**Comment by omo50** [comment]
seems to be fixed awhile ago
