### ISSUE TITLE
Idea to get all the mash-ups

### ISSUE THREAD

**Issue by CART5744** [ViolaFlower/Re-Console#62]
I have an idea to get all the maps and mash-up although I don't know if it works, the idea is that someone buys them for minecraft bedrock and then creates the worlds and puts the option of oblligatory textures in the creation of the world, according to my experience the world with the texture should be saved in the deepest files of minecraft bedrock,  Although if that doesn't work, what is certain is that in the deepest files those textures should be saved, what is certain is that in the deepest files, it is necessary toI have an idea to get all the maps and mash-up although I don't know if it works, the idea is that someone buys them for minecraft bedrock and then creates the worlds and puts the option of oblligatory textures in the creation of the world, according to my experience the world with the texture should be saved in the deepest files of minecraft bedrock,  Although if that doesn't work, what is certain is that in the deepest files those textures should be saved, what is certain is that in the deepest files, it is necessary toI have an idea to get all the maps and mash-up although I don't know if it works, the idea is that someone buys them for minecraft bedrock and then creates the worlds and puts the option of oblligatory textures in the creation of the world, according to my experience the world with the texture should be saved in the deepest files of minecraft bedrock,  Although if that doesn't work, what is certain is that in the deepest files those textures should be saved, what is certain is that in the deepest files, it is necessary to   Although if that doesn't work, what is certain is that in the deepest files those textures should be saved, what will remain is the most important thing in the files.I have an idea to get all the maps and mash-up although I don't know if it works, the idea is that someone buys them for minecraft bedrock and then creates the worlds and puts the option of oblligatory textures in the creation of the world, according to my experience the world with the texture should be saved in the deepest files of minecraft bedrock,  Although if that doesn't work, what is certain is that in the deepest files those textures should be saved, what would remain is that Transform them for java with an online converter or something, and edit them for re console

**Comment by omo50** [comment]
This is the last time I'm gonna say to stop giving suggestions via the issue tracker. Join the discord.

**Comment by CART5744** [comment]
> This is the last time I'm gonna say to stop giving suggestions via the issue tracker. Join the discord.

I'm sorry I seriously didn't know it couldn't be done, I'll do it with discord gladlyI'm sorry I seriously didn't know it couldn't be done, I'll do it with discord gladly 👍
