### ISSUE TITLE
[Resource Pack Suggestion] Default Dark Mode

### ISSUE THREAD

**Issue by arichornlover** [ViolaFlower/Re-Console#68]
I got a request to include NebuIr’s Default Dark Mode resource pack! (1.20.2+)
https://github.com/nebuIr/Default-Dark-Mode
![336294762-41e4b8ce-630b-4fff-8240-89fd7f82ef3c](https://github.com/ViolaFlower/Re-Console/assets/78001398/644b0527-2a52-447f-a735-755fea470f69)
I manually modified every **Legacy4J** textures related to the GUI in the resource pack to support Dark Mode

However, NebuIr didn’t update the resource pack so **Legacy4J** Dark Mode Textures may not be present in their recent release of the Resource Pack so I published my own version that includes the Legacy4J Dark Mode textures!
url: https://github.com/arichornlover/Default-Dark-Mode/releases/download/2024.6.5-beta/Default-Dark-Mode-1.20.2+-2024.6.5BETA.zip
Edit: URL has been updated due to modifications to other textures

and let me know if **Legacy4J** breaks the resource pack in the future, so I could fix it. But for now it works with the most recent versions of the mod (1.6.6 & 1.6.7).

**Comment by omo50** [comment]
If this would be added to the official dark mode resource pack, it'd be considered as an optional add-on in the wiki. Although it doesn't fully fit the theme to be included by default

It looks cool though, good work
