### ISSUE TITLE
invisible mob(s)

### ISSUE THREAD

**Issue by prizedd** [ViolaFlower/Re-Console#70]
while playing on the re-console 1.20.4 version i have no problem seeing the new/pigman version of the piglin mobs, but after updating my modpack to 1.20.6, i take a look at the piglins and theyre completely invisible, besides some having armor equipped and it apperaing to be floating

**Comment by omo50** [comment]
i will look into this soon

**Comment by MB4385** [comment]
This issue seems to happen when version 1.2.16 or higher of the Immediately Fast mod is installed
Removing the mod or downgrading to 1.2.15 or earlier fixes the problem

**Comment by intergrav** [comment]
may be related to https://github.com/RaphiMC/ImmediatelyFast/issues/228
