### ISSUE TITLE
Re-Console Resources pack doesn't have "console edition" title

### ISSUE THREAD

**Issue by ReaLeCHL** [ViolaFlower/Re-Console#71]
https://github.com/ViolaFlower/Re-Console/assets/165544616/f5a39230-7dd2-46e7-a771-6c5af4f1f653

In previous versions they used to have another texture
![Screenshot_1](https://github.com/ViolaFlower/Re-Console/assets/165544616/d3550544-5809-409d-b780-b027ae002570)

**Comment by omo50** [comment]
intentional
