### ISSUE TITLE
Nintendo switch pro controller connected but not working

### ISSUE THREAD

**Issue by kalebpikachu10** [ViolaFlower/Re-Console#72]
hi i'm having trouble with your Minecraft Modpack game when i try to use my Nintendo switch pro controller to play your Modpack game it will connected but not work when i try to press buttons on the controller i hope this issue will be fix soon as possible.

**Comment by omo50** [comment]
can you stop closing and re-opening this issue??

this is a L4J issue, not a re-console one

**Comment by kalebpikachu10** [comment]
> can you stop closing and re-opening this issue??
> 
> this is a L4J issue, not a re-console one
Sorry about that just trying to get proof of this Issue:(
