### ISSUE TITLE
[feature request] Split screen support

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [ViolaFlower/Re-Console#73]
If another controller is connected to the PC running re-console. The user of the second controller can join the game as player 2, and the screen will be split in half, allowing multiple people to play the game at the same time locally. Similar to how legacy console editions do their split screen.

**Comment by omo50** [comment]
This can be done via the Nucleus Co-op app, not on our end.

**Comment by Rushmore75** [comment]
Except nucleus coop don't work well :/ ...
