### ISSUE TITLE
cannot download any version of 1.20.6 of re-console

### ISSUE THREAD

**Issue by prizedd** [ViolaFlower/Re-Console#77]
as i try to download any version of the modpack besides 1.20.4 i get an error saying An error occurred Incorrect Sha1 hash for download: d518b23dd5a76794da4884abe57867a9ef572616 != 5cbd2b51a710d326a7568aeaec6

**Comment by intergrav** [comment]
this is being fixed as of right now :) new version with a hash fix should be published soon

**Comment by prizedd** [comment]
thanks for all the communication yall been on point lately
