### ISSUE TITLE
Only One Tutorial World Option Showing Up in Create Menu

### ISSUE THREAD

**Issue by billhasarrived** [ViolaFlower/Re-Console#78]
I had just updated to the latest version released today, and I noticed there was only one tutorial world option in the create menu. I loaded it up, and it is the latest tutorial world. 

Should be easily reproducible, I just installed the newest version and there was no other options. 
Feel free to close this issue if this was intentional.

![Screenshot 2024-06-10 194820](https://github.com/ViolaFlower/Re-Console/assets/19159496/6385e2a9-25a0-45b6-9603-378d723bfe9c)

**Comment by omo50** [comment]
intentional, other tutorial worlds are planned as an addon soon
