### ISSUE TITLE
Can't See Any Old Tutorial Worlds

### ISSUE THREAD

**Issue by YTDJEnder** [ViolaFlower/Re-Console#80]
I can load into the tutorial world that's under the New World option in the menu, but I can't see any of the older tutorial worlds. Is there a way to fix this? I have the latest Re-Console pack installed.
![Screenshot 2024-06-14 004829](https://github.com/ViolaFlower/Re-Console/assets/58960451/a54938ac-2260-45bd-a86e-634c327d0bcf)
![Screenshot 2024-06-14 004843](https://github.com/ViolaFlower/Re-Console/assets/58960451/b52644b2-88a8-44f3-9547-cf8fee7d194e)

**Comment by omo50** [comment]
This is intentional; the tutorial worlds will be added as an optional resource pack in the future
