### ISSUE TITLE
Odd issue with open chest entity.

### ISSUE THREAD

**Issue by mzovjen** [ViolaFlower/Re-Console#81]
When open, chests seem to be using the wrong texture on the top part. Works fine on vanilla and fabulously optimized, seemingly an issue with the modpack. This isn't a resource pack issue, the chest texture is still the same accross vanilla, programmer art and pacp.

Issue 70 had entity model issues caused by immediatelyfast, so maybe could start looking there. 

![2024-06-14_20 41 04](https://github.com/ViolaFlower/Re-Console/assets/172861616/fa37af40-5d09-4087-a8c0-eb1a2f2ddfbb)
![2024-06-14_20 41 02](https://github.com/ViolaFlower/Re-Console/assets/172861616/ec036fa8-5572-427e-8f3b-dc2e7d6adfa0)

**Comment by mzovjen** [comment]
Update: It is caused by immediatelyfast. Immediately fixed by turning it off.
![2024-06-14_21 04 40](https://github.com/ViolaFlower/Re-Console/assets/172861616/ceb8cab6-b6eb-43a3-a27d-e24c271eb72e)

**Comment by omo50** [comment]
@intergrav mind looking at this?

**Comment by omo50** [comment]
Fixed in 0.6 from what i can see.
