### ISSUE TITLE
Moderner Beta Settings  Unable to select different preset than Beta 1.7.3 due to issue in controller support

### ISSUE THREAD

**Issue by TacticianTilted** [ViolaFlower/Re-Console#82]
when in menu to select different moderner beta world preset I find the preset I want I clicked A on controller didn't work I tried pressing enter on keyboard. nothing happened. I tried all controller buttons nothing

**Comment by omo50** [comment]
Moderner Beta is semi broken due to L4J. This would be better as something for L4J, as a request for compatibility
