### ISSUE TITLE
0.5.6 thingymabobers

### ISSUE THREAD

**Issue by omo50** [ViolaFlower/Re-Console#83]
- Add Re-Console Resources + Tutorial Worlds (tutorial worlds disabled by default)
- Disable Programmer Art and PACP by default
- Disable Enhanced Signs in the EBE config to fix the text being misaligned (#19)
- Remove Legacy Mipmaps (causes issues with PACP textures, isn't super accurate and does make the game look worse atm)
- Remove CICADA (lib mod that does nothing for the pack)
- Remove Language Reload (breaks certain translations and causes issues)

**Comment by omo50** [comment]
Also, I think we should start work on the wiki.

Anyone have anything to suggest? If so, put it here

**Comment by contrarybaton60** [comment]
I like to think that a "centralized" wiki would be a good idea, for both Legacy4J and Re-Console (and maybe others too)

**Comment by Permdog99** [comment]
The next update for Legacy Mipmaps will be changing mipmapping to make it more accurate and allow it to be disabled via a config

**Comment by contrarybaton60** [comment]
> The next update for Legacy Mipmaps will be changing mipmapping to make it more accurate and allow it to be disabled via a config
Would it also be possible to "lessen" the mipmaps?

**Comment by Permdog99** [comment]
> > The next update for Legacy Mipmaps will be changing mipmapping to make it more accurate and allow it to be disabled via a config
> 
> Would it also be possible to "lessen" the mipmaps?

Technically. Idk if this will be in the next update, but I plan to add PS4 Jappa style mipmapping as an option, which is basically a much smoother version of Programmer Art's mipmapping

**Comment by omo50** [comment]
> The next update for Legacy Mipmaps will be changing mipmapping to make it more accurate and allow it to be disabled via a config

Id hope this would come soon. Currently it is still slated to be removed, although itll be re-considered once this update is out

**Comment by Cjnator38** [comment]
> > The next update for Legacy Mipmaps will be changing mipmapping to make it more accurate and allow it to be disabled via a config
> 
> Id hope this would come soon. Currently it is still slated to be removed, although itll be re-considered once this update is out

I know I'm a bit late to this but now that Legacy Mipmaps 1.2 has been out for a bit (1.2.2 being the current release) will this still be considered? If it is considered, Nostalgic Tweaks "Remove Mipmap Texturing" should be disabled.
