### ISSUE TITLE
Controller doesn't work on macOS

### ISSUE THREAD

**Issue by mrzumo** [ViolaFlower/Re-Console#88]
Macbook air m2, macOS Sonoma.

Having a controller does nothing. Changing the controller api to 2 crashes the game with the following error: https://mclo.gs/0RAMsNj

**Comment by intergrav** [comment]
This would be an issue for Legacy4J: https://github.com/Wilyicaro/Legacy-Minecraft

**Comment by omo50** [comment]
Closing as this would be better suited for the Legacy4J repo, as noted above
