### ISSUE TITLE
MacOS 15.0 (Possibly Earlier) Lacking Controller Support

### ISSUE THREAD

**Issue by Nodysey** [ViolaFlower/Re-Console#90]
### Background Information:
- Launcher: Prism Launcher
- Minecraft Version: 1.20.6
- OS: MacOS 15.0 Beta 1
- Controller: Xbox One S Controller (Micro-USB)
- Java Version: 21.0.3

Upon switching the controller input meathod to the second option, the modpack crashes. The first option doesn't work at all.

**Comment by omo50** [comment]
Does this occur with just legacy4J

**Comment by Nodysey** [comment]
No, but I can try. Adding an external mod (like controllify) works but crashes whenever the pause screen is enabled (due to the ui changer mod).

**Comment by omo50** [comment]
@Nodysey do you have SDL installed?

**Comment by omo50** [comment]
Also, is this on 1.20.4 or 1.20.6

**Comment by omo50** [comment]
this issue seems dead. If still occuring, report to the Legacy4J issue tracker
