### ISSUE TITLE
How Do You Use The E4MC Mod? 

### ISSUE THREAD

**Issue by TheGamingMarioD** [ViolaFlower/Re-Console#91]
Whenever I set up LAN in a world with experimental features, I copy/paste the link as the server address for my Friends but it doesn't work. The Modpack versions are not mismatched and the firewall isn't blocking any connections on any of our Pc's. All it says is that the server doesn't exist, lost connection or something along those lines. Am I doing this wrong?

**Comment by omo50** [comment]
I believe this would be an issue to report to the e4mc repo. We have considered switching to World Host in the future once Legacy4J and World Host are compatible.

However, please ask questions in the discord server rather than GitHub, you'll get a quicker response there
