### ISSUE TITLE
Villagers allow you to buy way more than you should

### ISSUE THREAD

**Issue by IvanBoss3000** [ViolaFlower/Re-Console#93]
Villagers will let you buy more than you should if you use shift click to buy an item. Normally there is a limit to how many times you can buy / sell items.

Before buying
![image](https://github.com/ViolaFlower/Re-Console/assets/93098416/816f17e9-d4c7-4320-bd76-2bb0d4ee43a7)

After Buying
![image](https://github.com/ViolaFlower/Re-Console/assets/93098416/e5595b3e-3400-4ba2-8de5-3e87f00b29f9)
*alot more on the ground*

It also gives the same ammount of xp as if the player bought that many items.

**Comment by omo50** [comment]
Does this occur with *just* Legacy4J? Nothing in Re-Console should affect villager trading

**Comment by IvanBoss3000** [comment]
Yeah, I think its just an issue with Leagacy4J.
