### ISSUE TITLE
Opening Load Save screen while FastQuit is still saving causes crash

### ISSUE THREAD

**Issue by Cjnator38** [ViolaFlower/Re-Console#94]
https://github.com/ViolaFlower/Re-Console/assets/39870226/f15f03ab-a5db-44e0-9f2a-479f329196ea

https://mclo.gs/JptytuY

**Comment by Cjnator38** [comment]
I don't know if this relates at all, but disabling autosave with L4J combined with FastQuit(?) seems to incorrectly save region files somehow, causing a good amount of the chunks to be placed incorrectly
![2024-07-06_16 29 28](https://github.com/ViolaFlower/Re-Console/assets/39870226/a59977d3-4205-42ac-bf73-b0569c12ce8c)

![2024-07-06_16 32 04](https://github.com/ViolaFlower/Re-Console/assets/39870226/84a63669-07e5-4417-927e-6ae8596899a9)

It's unclear whether or not this is an issue with combining Legacy4J and FastQuit, an issue with the mods individually, or another mod in the modpack.

https://mclo.gs/7K2fb2w

**Comment by omo50** [comment]
I'll probably do some form of testing eventually

**Comment by omo50** [comment]
just to make my life easier: does this occur in 0.6? @Cjnator38

**Comment by Cjnator38** [comment]
The load save crash is fixed, but the chunk saving error still occurs. That issue is quit difficult to replicate as it seems to happen randomly

**Comment by omo50** [comment]
Thanks, I'll try fixing this in 0.6.1 (patch to fix some oversights and bugs in 0.6.0).

**Comment by Cjnator38** [comment]
I'm gonna split the chunk saving bug to a separate report as I've gotten it to happen without FastQuit

**Comment by omo50** [comment]
should be fixed in 0.7.0.beta.1
