### ISSUE TITLE
Nintendo Switch and WiiU Icons being inverted on non inverted icons mode

### ISSUE THREAD

**Issue by SpacePizzazzisda1** [ViolaFlower/Re-Console#96]
![Screenshot 2024-07-08 231214](https://github.com/ViolaFlower/Re-Console/assets/141004036/02923685-bfa7-4400-8d1b-b19ca59c35cb)
![Screenshot 2024-07-08 225143](https://github.com/ViolaFlower/Re-Console/assets/141004036/749f3a2c-71fd-4f3a-8a73-5780f08f6d75)

**Comment by omo50** [comment]
I don't see the problem here; what's the issue?
This would be something to report at the Legacy4J repo, not here by the way
